/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as DemoWindfarmRouteImport } from './routes/demo/windfarm'
import { Route as ProtectedTurbinesRouteImport } from './routes/_protected.turbines'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedReportsRouteImport } from './routes/_protected.reports'
import { Route as ProtectedPortfoliosRouteImport } from './routes/_protected.portfolios'
import { Route as ProtectedMapRouteImport } from './routes/_protected.map'
import { Route as ProtectedHelpRouteImport } from './routes/_protected.help'
import { Route as ProtectedExportRouteImport } from './routes/_protected.export'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedComparisonRouteImport } from './routes/_protected.comparison'
import { Route as ProtectedAnomaliesRouteImport } from './routes/_protected.anomalies'
import { Route as ProtectedAlertsRouteImport } from './routes/_protected.alerts'
import { Route as ProtectedWindFarmsIndexRouteImport } from './routes/_protected.wind-farms.index'
import { Route as ProtectedWindFarmsWindfarmIdRouteImport } from './routes/_protected.wind-farms.$windfarmId'
import { Route as ProtectedPortfoliosPortfolioIdRouteImport } from './routes/_protected.portfolios.$portfolioId'
import { Route as ProtectedAnalyticsWeatherRouteImport } from './routes/_protected.analytics.weather'
import { Route as ProtectedAnalyticsRevenueRouteImport } from './routes/_protected.analytics.revenue'
import { Route as ProtectedAnalyticsPerformanceRouteImport } from './routes/_protected.analytics.performance'
import { Route as ProtectedAnalyticsGenerationRouteImport } from './routes/_protected.analytics.generation'
import { Route as ProtectedWindFarmsWindfarmIdIndexRouteImport } from './routes/_protected.wind-farms.$windfarmId.index'
import { Route as ProtectedWindFarmsWindfarmIdWeatherRouteImport } from './routes/_protected.wind-farms.$windfarmId.weather'
import { Route as ProtectedWindFarmsWindfarmIdReportRouteImport } from './routes/_protected.wind-farms.$windfarmId.report'
import { Route as ProtectedWindFarmsWindfarmIdMarketRouteImport } from './routes/_protected.wind-farms.$windfarmId.market'
import { Route as ProtectedWindFarmsWindfarmIdGenerationRouteImport } from './routes/_protected.wind-farms.$windfarmId.generation'
import { Route as ProtectedWindFarmsWindfarmIdBenchmarkingRouteImport } from './routes/_protected.wind-farms.$windfarmId.benchmarking'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWindfarmRoute = DemoWindfarmRouteImport.update({
  id: '/windfarm',
  path: '/windfarm',
  getParentRoute: () => DemoRoute,
} as any)
const ProtectedTurbinesRoute = ProtectedTurbinesRouteImport.update({
  id: '/turbines',
  path: '/turbines',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPortfoliosRoute = ProtectedPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMapRoute = ProtectedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHelpRoute = ProtectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExportRoute = ProtectedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedComparisonRoute = ProtectedComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnomaliesRoute = ProtectedAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAlertsRoute = ProtectedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWindFarmsIndexRoute = ProtectedWindFarmsIndexRouteImport.update({
  id: '/wind-farms/',
  path: '/wind-farms/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWindFarmsWindfarmIdRoute =
  ProtectedWindFarmsWindfarmIdRouteImport.update({
    id: '/wind-farms/$windfarmId',
    path: '/wind-farms/$windfarmId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPortfoliosPortfolioIdRoute =
  ProtectedPortfoliosPortfolioIdRouteImport.update({
    id: '/$portfolioId',
    path: '/$portfolioId',
    getParentRoute: () => ProtectedPortfoliosRoute,
  } as any)
const ProtectedAnalyticsWeatherRoute =
  ProtectedAnalyticsWeatherRouteImport.update({
    id: '/analytics/weather',
    path: '/analytics/weather',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAnalyticsRevenueRoute =
  ProtectedAnalyticsRevenueRouteImport.update({
    id: '/analytics/revenue',
    path: '/analytics/revenue',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAnalyticsPerformanceRoute =
  ProtectedAnalyticsPerformanceRouteImport.update({
    id: '/analytics/performance',
    path: '/analytics/performance',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAnalyticsGenerationRoute =
  ProtectedAnalyticsGenerationRouteImport.update({
    id: '/analytics/generation',
    path: '/analytics/generation',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdIndexRoute =
  ProtectedWindFarmsWindfarmIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdWeatherRoute =
  ProtectedWindFarmsWindfarmIdWeatherRouteImport.update({
    id: '/weather',
    path: '/weather',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdReportRoute =
  ProtectedWindFarmsWindfarmIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdMarketRoute =
  ProtectedWindFarmsWindfarmIdMarketRouteImport.update({
    id: '/market',
    path: '/market',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdGenerationRoute =
  ProtectedWindFarmsWindfarmIdGenerationRouteImport.update({
    id: '/generation',
    path: '/generation',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdBenchmarkingRoute =
  ProtectedWindFarmsWindfarmIdBenchmarkingRouteImport.update({
    id: '/benchmarking',
    path: '/benchmarking',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/alerts': typeof ProtectedAlertsRoute
  '/anomalies': typeof ProtectedAnomaliesRoute
  '/comparison': typeof ProtectedComparisonRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/export': typeof ProtectedExportRoute
  '/help': typeof ProtectedHelpRoute
  '/map': typeof ProtectedMapRoute
  '/portfolios': typeof ProtectedPortfoliosRouteWithChildren
  '/reports': typeof ProtectedReportsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/turbines': typeof ProtectedTurbinesRoute
  '/demo/windfarm': typeof DemoWindfarmRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/analytics/generation': typeof ProtectedAnalyticsGenerationRoute
  '/analytics/performance': typeof ProtectedAnalyticsPerformanceRoute
  '/analytics/revenue': typeof ProtectedAnalyticsRevenueRoute
  '/analytics/weather': typeof ProtectedAnalyticsWeatherRoute
  '/portfolios/$portfolioId': typeof ProtectedPortfoliosPortfolioIdRoute
  '/wind-farms/$windfarmId': typeof ProtectedWindFarmsWindfarmIdRouteWithChildren
  '/wind-farms/': typeof ProtectedWindFarmsIndexRoute
  '/wind-farms/$windfarmId/benchmarking': typeof ProtectedWindFarmsWindfarmIdBenchmarkingRoute
  '/wind-farms/$windfarmId/generation': typeof ProtectedWindFarmsWindfarmIdGenerationRoute
  '/wind-farms/$windfarmId/market': typeof ProtectedWindFarmsWindfarmIdMarketRoute
  '/wind-farms/$windfarmId/report': typeof ProtectedWindFarmsWindfarmIdReportRoute
  '/wind-farms/$windfarmId/weather': typeof ProtectedWindFarmsWindfarmIdWeatherRoute
  '/wind-farms/$windfarmId/': typeof ProtectedWindFarmsWindfarmIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/alerts': typeof ProtectedAlertsRoute
  '/anomalies': typeof ProtectedAnomaliesRoute
  '/comparison': typeof ProtectedComparisonRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/export': typeof ProtectedExportRoute
  '/help': typeof ProtectedHelpRoute
  '/map': typeof ProtectedMapRoute
  '/portfolios': typeof ProtectedPortfoliosRouteWithChildren
  '/reports': typeof ProtectedReportsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/turbines': typeof ProtectedTurbinesRoute
  '/demo/windfarm': typeof DemoWindfarmRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/analytics/generation': typeof ProtectedAnalyticsGenerationRoute
  '/analytics/performance': typeof ProtectedAnalyticsPerformanceRoute
  '/analytics/revenue': typeof ProtectedAnalyticsRevenueRoute
  '/analytics/weather': typeof ProtectedAnalyticsWeatherRoute
  '/portfolios/$portfolioId': typeof ProtectedPortfoliosPortfolioIdRoute
  '/wind-farms': typeof ProtectedWindFarmsIndexRoute
  '/wind-farms/$windfarmId/benchmarking': typeof ProtectedWindFarmsWindfarmIdBenchmarkingRoute
  '/wind-farms/$windfarmId/generation': typeof ProtectedWindFarmsWindfarmIdGenerationRoute
  '/wind-farms/$windfarmId/market': typeof ProtectedWindFarmsWindfarmIdMarketRoute
  '/wind-farms/$windfarmId/report': typeof ProtectedWindFarmsWindfarmIdReportRoute
  '/wind-farms/$windfarmId/weather': typeof ProtectedWindFarmsWindfarmIdWeatherRoute
  '/wind-farms/$windfarmId': typeof ProtectedWindFarmsWindfarmIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/alerts': typeof ProtectedAlertsRoute
  '/_protected/anomalies': typeof ProtectedAnomaliesRoute
  '/_protected/comparison': typeof ProtectedComparisonRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/export': typeof ProtectedExportRoute
  '/_protected/help': typeof ProtectedHelpRoute
  '/_protected/map': typeof ProtectedMapRoute
  '/_protected/portfolios': typeof ProtectedPortfoliosRouteWithChildren
  '/_protected/reports': typeof ProtectedReportsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/turbines': typeof ProtectedTurbinesRoute
  '/demo/windfarm': typeof DemoWindfarmRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/_protected/analytics/generation': typeof ProtectedAnalyticsGenerationRoute
  '/_protected/analytics/performance': typeof ProtectedAnalyticsPerformanceRoute
  '/_protected/analytics/revenue': typeof ProtectedAnalyticsRevenueRoute
  '/_protected/analytics/weather': typeof ProtectedAnalyticsWeatherRoute
  '/_protected/portfolios/$portfolioId': typeof ProtectedPortfoliosPortfolioIdRoute
  '/_protected/wind-farms/$windfarmId': typeof ProtectedWindFarmsWindfarmIdRouteWithChildren
  '/_protected/wind-farms/': typeof ProtectedWindFarmsIndexRoute
  '/_protected/wind-farms/$windfarmId/benchmarking': typeof ProtectedWindFarmsWindfarmIdBenchmarkingRoute
  '/_protected/wind-farms/$windfarmId/generation': typeof ProtectedWindFarmsWindfarmIdGenerationRoute
  '/_protected/wind-farms/$windfarmId/market': typeof ProtectedWindFarmsWindfarmIdMarketRoute
  '/_protected/wind-farms/$windfarmId/report': typeof ProtectedWindFarmsWindfarmIdReportRoute
  '/_protected/wind-farms/$windfarmId/weather': typeof ProtectedWindFarmsWindfarmIdWeatherRoute
  '/_protected/wind-farms/$windfarmId/': typeof ProtectedWindFarmsWindfarmIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/alerts'
    | '/anomalies'
    | '/comparison'
    | '/dashboard'
    | '/export'
    | '/help'
    | '/map'
    | '/portfolios'
    | '/reports'
    | '/settings'
    | '/turbines'
    | '/demo/windfarm'
    | '/invitation/$token'
    | '/analytics/generation'
    | '/analytics/performance'
    | '/analytics/revenue'
    | '/analytics/weather'
    | '/portfolios/$portfolioId'
    | '/wind-farms/$windfarmId'
    | '/wind-farms/'
    | '/wind-farms/$windfarmId/benchmarking'
    | '/wind-farms/$windfarmId/generation'
    | '/wind-farms/$windfarmId/market'
    | '/wind-farms/$windfarmId/report'
    | '/wind-farms/$windfarmId/weather'
    | '/wind-farms/$windfarmId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/alerts'
    | '/anomalies'
    | '/comparison'
    | '/dashboard'
    | '/export'
    | '/help'
    | '/map'
    | '/portfolios'
    | '/reports'
    | '/settings'
    | '/turbines'
    | '/demo/windfarm'
    | '/invitation/$token'
    | '/analytics/generation'
    | '/analytics/performance'
    | '/analytics/revenue'
    | '/analytics/weather'
    | '/portfolios/$portfolioId'
    | '/wind-farms'
    | '/wind-farms/$windfarmId/benchmarking'
    | '/wind-farms/$windfarmId/generation'
    | '/wind-farms/$windfarmId/market'
    | '/wind-farms/$windfarmId/report'
    | '/wind-farms/$windfarmId/weather'
    | '/wind-farms/$windfarmId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_protected/alerts'
    | '/_protected/anomalies'
    | '/_protected/comparison'
    | '/_protected/dashboard'
    | '/_protected/export'
    | '/_protected/help'
    | '/_protected/map'
    | '/_protected/portfolios'
    | '/_protected/reports'
    | '/_protected/settings'
    | '/_protected/turbines'
    | '/demo/windfarm'
    | '/invitation/$token'
    | '/_protected/analytics/generation'
    | '/_protected/analytics/performance'
    | '/_protected/analytics/revenue'
    | '/_protected/analytics/weather'
    | '/_protected/portfolios/$portfolioId'
    | '/_protected/wind-farms/$windfarmId'
    | '/_protected/wind-farms/'
    | '/_protected/wind-farms/$windfarmId/benchmarking'
    | '/_protected/wind-farms/$windfarmId/generation'
    | '/_protected/wind-farms/$windfarmId/market'
    | '/_protected/wind-farms/$windfarmId/report'
    | '/_protected/wind-farms/$windfarmId/weather'
    | '/_protected/wind-farms/$windfarmId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/windfarm': {
      id: '/demo/windfarm'
      path: '/windfarm'
      fullPath: '/demo/windfarm'
      preLoaderRoute: typeof DemoWindfarmRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_protected/turbines': {
      id: '/_protected/turbines'
      path: '/turbines'
      fullPath: '/turbines'
      preLoaderRoute: typeof ProtectedTurbinesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/portfolios': {
      id: '/_protected/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof ProtectedPortfoliosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/map': {
      id: '/_protected/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof ProtectedMapRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/help': {
      id: '/_protected/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ProtectedHelpRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/export': {
      id: '/_protected/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ProtectedExportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/comparison': {
      id: '/_protected/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ProtectedComparisonRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/anomalies': {
      id: '/_protected/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof ProtectedAnomaliesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/alerts': {
      id: '/_protected/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof ProtectedAlertsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/wind-farms/': {
      id: '/_protected/wind-farms/'
      path: '/wind-farms'
      fullPath: '/wind-farms/'
      preLoaderRoute: typeof ProtectedWindFarmsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/wind-farms/$windfarmId': {
      id: '/_protected/wind-farms/$windfarmId'
      path: '/wind-farms/$windfarmId'
      fullPath: '/wind-farms/$windfarmId'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/portfolios/$portfolioId': {
      id: '/_protected/portfolios/$portfolioId'
      path: '/$portfolioId'
      fullPath: '/portfolios/$portfolioId'
      preLoaderRoute: typeof ProtectedPortfoliosPortfolioIdRouteImport
      parentRoute: typeof ProtectedPortfoliosRoute
    }
    '/_protected/analytics/weather': {
      id: '/_protected/analytics/weather'
      path: '/analytics/weather'
      fullPath: '/analytics/weather'
      preLoaderRoute: typeof ProtectedAnalyticsWeatherRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics/revenue': {
      id: '/_protected/analytics/revenue'
      path: '/analytics/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof ProtectedAnalyticsRevenueRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics/performance': {
      id: '/_protected/analytics/performance'
      path: '/analytics/performance'
      fullPath: '/analytics/performance'
      preLoaderRoute: typeof ProtectedAnalyticsPerformanceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics/generation': {
      id: '/_protected/analytics/generation'
      path: '/analytics/generation'
      fullPath: '/analytics/generation'
      preLoaderRoute: typeof ProtectedAnalyticsGenerationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/wind-farms/$windfarmId/': {
      id: '/_protected/wind-farms/$windfarmId/'
      path: '/'
      fullPath: '/wind-farms/$windfarmId/'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdIndexRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
    '/_protected/wind-farms/$windfarmId/weather': {
      id: '/_protected/wind-farms/$windfarmId/weather'
      path: '/weather'
      fullPath: '/wind-farms/$windfarmId/weather'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdWeatherRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
    '/_protected/wind-farms/$windfarmId/report': {
      id: '/_protected/wind-farms/$windfarmId/report'
      path: '/report'
      fullPath: '/wind-farms/$windfarmId/report'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdReportRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
    '/_protected/wind-farms/$windfarmId/market': {
      id: '/_protected/wind-farms/$windfarmId/market'
      path: '/market'
      fullPath: '/wind-farms/$windfarmId/market'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdMarketRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
    '/_protected/wind-farms/$windfarmId/generation': {
      id: '/_protected/wind-farms/$windfarmId/generation'
      path: '/generation'
      fullPath: '/wind-farms/$windfarmId/generation'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdGenerationRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
    '/_protected/wind-farms/$windfarmId/benchmarking': {
      id: '/_protected/wind-farms/$windfarmId/benchmarking'
      path: '/benchmarking'
      fullPath: '/wind-farms/$windfarmId/benchmarking'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdBenchmarkingRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
  }
}

interface ProtectedPortfoliosRouteChildren {
  ProtectedPortfoliosPortfolioIdRoute: typeof ProtectedPortfoliosPortfolioIdRoute
}

const ProtectedPortfoliosRouteChildren: ProtectedPortfoliosRouteChildren = {
  ProtectedPortfoliosPortfolioIdRoute: ProtectedPortfoliosPortfolioIdRoute,
}

const ProtectedPortfoliosRouteWithChildren =
  ProtectedPortfoliosRoute._addFileChildren(ProtectedPortfoliosRouteChildren)

interface ProtectedWindFarmsWindfarmIdRouteChildren {
  ProtectedWindFarmsWindfarmIdBenchmarkingRoute: typeof ProtectedWindFarmsWindfarmIdBenchmarkingRoute
  ProtectedWindFarmsWindfarmIdGenerationRoute: typeof ProtectedWindFarmsWindfarmIdGenerationRoute
  ProtectedWindFarmsWindfarmIdMarketRoute: typeof ProtectedWindFarmsWindfarmIdMarketRoute
  ProtectedWindFarmsWindfarmIdReportRoute: typeof ProtectedWindFarmsWindfarmIdReportRoute
  ProtectedWindFarmsWindfarmIdWeatherRoute: typeof ProtectedWindFarmsWindfarmIdWeatherRoute
  ProtectedWindFarmsWindfarmIdIndexRoute: typeof ProtectedWindFarmsWindfarmIdIndexRoute
}

const ProtectedWindFarmsWindfarmIdRouteChildren: ProtectedWindFarmsWindfarmIdRouteChildren =
  {
    ProtectedWindFarmsWindfarmIdBenchmarkingRoute:
      ProtectedWindFarmsWindfarmIdBenchmarkingRoute,
    ProtectedWindFarmsWindfarmIdGenerationRoute:
      ProtectedWindFarmsWindfarmIdGenerationRoute,
    ProtectedWindFarmsWindfarmIdMarketRoute:
      ProtectedWindFarmsWindfarmIdMarketRoute,
    ProtectedWindFarmsWindfarmIdReportRoute:
      ProtectedWindFarmsWindfarmIdReportRoute,
    ProtectedWindFarmsWindfarmIdWeatherRoute:
      ProtectedWindFarmsWindfarmIdWeatherRoute,
    ProtectedWindFarmsWindfarmIdIndexRoute:
      ProtectedWindFarmsWindfarmIdIndexRoute,
  }

const ProtectedWindFarmsWindfarmIdRouteWithChildren =
  ProtectedWindFarmsWindfarmIdRoute._addFileChildren(
    ProtectedWindFarmsWindfarmIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAlertsRoute: typeof ProtectedAlertsRoute
  ProtectedAnomaliesRoute: typeof ProtectedAnomaliesRoute
  ProtectedComparisonRoute: typeof ProtectedComparisonRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedExportRoute: typeof ProtectedExportRoute
  ProtectedHelpRoute: typeof ProtectedHelpRoute
  ProtectedMapRoute: typeof ProtectedMapRoute
  ProtectedPortfoliosRoute: typeof ProtectedPortfoliosRouteWithChildren
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTurbinesRoute: typeof ProtectedTurbinesRoute
  ProtectedAnalyticsGenerationRoute: typeof ProtectedAnalyticsGenerationRoute
  ProtectedAnalyticsPerformanceRoute: typeof ProtectedAnalyticsPerformanceRoute
  ProtectedAnalyticsRevenueRoute: typeof ProtectedAnalyticsRevenueRoute
  ProtectedAnalyticsWeatherRoute: typeof ProtectedAnalyticsWeatherRoute
  ProtectedWindFarmsWindfarmIdRoute: typeof ProtectedWindFarmsWindfarmIdRouteWithChildren
  ProtectedWindFarmsIndexRoute: typeof ProtectedWindFarmsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAlertsRoute: ProtectedAlertsRoute,
  ProtectedAnomaliesRoute: ProtectedAnomaliesRoute,
  ProtectedComparisonRoute: ProtectedComparisonRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedExportRoute: ProtectedExportRoute,
  ProtectedHelpRoute: ProtectedHelpRoute,
  ProtectedMapRoute: ProtectedMapRoute,
  ProtectedPortfoliosRoute: ProtectedPortfoliosRouteWithChildren,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTurbinesRoute: ProtectedTurbinesRoute,
  ProtectedAnalyticsGenerationRoute: ProtectedAnalyticsGenerationRoute,
  ProtectedAnalyticsPerformanceRoute: ProtectedAnalyticsPerformanceRoute,
  ProtectedAnalyticsRevenueRoute: ProtectedAnalyticsRevenueRoute,
  ProtectedAnalyticsWeatherRoute: ProtectedAnalyticsWeatherRoute,
  ProtectedWindFarmsWindfarmIdRoute:
    ProtectedWindFarmsWindfarmIdRouteWithChildren,
  ProtectedWindFarmsIndexRoute: ProtectedWindFarmsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface DemoRouteChildren {
  DemoWindfarmRoute: typeof DemoWindfarmRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoWindfarmRoute: DemoWindfarmRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InvitationTokenRoute: InvitationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
