/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as DemoWindfarmRouteImport } from './routes/demo/windfarm'
import { Route as ProtectedPortfoliosRouteImport } from './routes/_protected.portfolios'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedComparisonRouteImport } from './routes/_protected.comparison'
import { Route as ProtectedWindFarmsIndexRouteImport } from './routes/_protected.wind-farms.index'
import { Route as ProtectedWindFarmsWindfarmIdRouteImport } from './routes/_protected.wind-farms.$windfarmId'
import { Route as ProtectedPortfoliosPortfolioIdRouteImport } from './routes/_protected.portfolios.$portfolioId'
import { Route as ProtectedWindFarmsWindfarmIdWeatherRouteImport } from './routes/_protected.wind-farms.$windfarmId.weather'
import { Route as ProtectedWindFarmsWindfarmIdMarketRouteImport } from './routes/_protected.wind-farms.$windfarmId.market'
import { Route as ProtectedWindFarmsWindfarmIdGenerationRouteImport } from './routes/_protected.wind-farms.$windfarmId.generation'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWindfarmRoute = DemoWindfarmRouteImport.update({
  id: '/windfarm',
  path: '/windfarm',
  getParentRoute: () => DemoRoute,
} as any)
const ProtectedPortfoliosRoute = ProtectedPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedComparisonRoute = ProtectedComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWindFarmsIndexRoute = ProtectedWindFarmsIndexRouteImport.update({
  id: '/wind-farms/',
  path: '/wind-farms/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWindFarmsWindfarmIdRoute =
  ProtectedWindFarmsWindfarmIdRouteImport.update({
    id: '/wind-farms/$windfarmId',
    path: '/wind-farms/$windfarmId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPortfoliosPortfolioIdRoute =
  ProtectedPortfoliosPortfolioIdRouteImport.update({
    id: '/$portfolioId',
    path: '/$portfolioId',
    getParentRoute: () => ProtectedPortfoliosRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdWeatherRoute =
  ProtectedWindFarmsWindfarmIdWeatherRouteImport.update({
    id: '/weather',
    path: '/weather',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdMarketRoute =
  ProtectedWindFarmsWindfarmIdMarketRouteImport.update({
    id: '/market',
    path: '/market',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)
const ProtectedWindFarmsWindfarmIdGenerationRoute =
  ProtectedWindFarmsWindfarmIdGenerationRouteImport.update({
    id: '/generation',
    path: '/generation',
    getParentRoute: () => ProtectedWindFarmsWindfarmIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/comparison': typeof ProtectedComparisonRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/portfolios': typeof ProtectedPortfoliosRouteWithChildren
  '/demo/windfarm': typeof DemoWindfarmRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/portfolios/$portfolioId': typeof ProtectedPortfoliosPortfolioIdRoute
  '/wind-farms/$windfarmId': typeof ProtectedWindFarmsWindfarmIdRouteWithChildren
  '/wind-farms/': typeof ProtectedWindFarmsIndexRoute
  '/wind-farms/$windfarmId/generation': typeof ProtectedWindFarmsWindfarmIdGenerationRoute
  '/wind-farms/$windfarmId/market': typeof ProtectedWindFarmsWindfarmIdMarketRoute
  '/wind-farms/$windfarmId/weather': typeof ProtectedWindFarmsWindfarmIdWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/comparison': typeof ProtectedComparisonRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/portfolios': typeof ProtectedPortfoliosRouteWithChildren
  '/demo/windfarm': typeof DemoWindfarmRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/portfolios/$portfolioId': typeof ProtectedPortfoliosPortfolioIdRoute
  '/wind-farms/$windfarmId': typeof ProtectedWindFarmsWindfarmIdRouteWithChildren
  '/wind-farms': typeof ProtectedWindFarmsIndexRoute
  '/wind-farms/$windfarmId/generation': typeof ProtectedWindFarmsWindfarmIdGenerationRoute
  '/wind-farms/$windfarmId/market': typeof ProtectedWindFarmsWindfarmIdMarketRoute
  '/wind-farms/$windfarmId/weather': typeof ProtectedWindFarmsWindfarmIdWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/comparison': typeof ProtectedComparisonRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/portfolios': typeof ProtectedPortfoliosRouteWithChildren
  '/demo/windfarm': typeof DemoWindfarmRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/_protected/portfolios/$portfolioId': typeof ProtectedPortfoliosPortfolioIdRoute
  '/_protected/wind-farms/$windfarmId': typeof ProtectedWindFarmsWindfarmIdRouteWithChildren
  '/_protected/wind-farms/': typeof ProtectedWindFarmsIndexRoute
  '/_protected/wind-farms/$windfarmId/generation': typeof ProtectedWindFarmsWindfarmIdGenerationRoute
  '/_protected/wind-farms/$windfarmId/market': typeof ProtectedWindFarmsWindfarmIdMarketRoute
  '/_protected/wind-farms/$windfarmId/weather': typeof ProtectedWindFarmsWindfarmIdWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/comparison'
    | '/dashboard'
    | '/portfolios'
    | '/demo/windfarm'
    | '/invitation/$token'
    | '/portfolios/$portfolioId'
    | '/wind-farms/$windfarmId'
    | '/wind-farms/'
    | '/wind-farms/$windfarmId/generation'
    | '/wind-farms/$windfarmId/market'
    | '/wind-farms/$windfarmId/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/comparison'
    | '/dashboard'
    | '/portfolios'
    | '/demo/windfarm'
    | '/invitation/$token'
    | '/portfolios/$portfolioId'
    | '/wind-farms/$windfarmId'
    | '/wind-farms'
    | '/wind-farms/$windfarmId/generation'
    | '/wind-farms/$windfarmId/market'
    | '/wind-farms/$windfarmId/weather'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_protected/comparison'
    | '/_protected/dashboard'
    | '/_protected/portfolios'
    | '/demo/windfarm'
    | '/invitation/$token'
    | '/_protected/portfolios/$portfolioId'
    | '/_protected/wind-farms/$windfarmId'
    | '/_protected/wind-farms/'
    | '/_protected/wind-farms/$windfarmId/generation'
    | '/_protected/wind-farms/$windfarmId/market'
    | '/_protected/wind-farms/$windfarmId/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/windfarm': {
      id: '/demo/windfarm'
      path: '/windfarm'
      fullPath: '/demo/windfarm'
      preLoaderRoute: typeof DemoWindfarmRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_protected/portfolios': {
      id: '/_protected/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof ProtectedPortfoliosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/comparison': {
      id: '/_protected/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ProtectedComparisonRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/wind-farms/': {
      id: '/_protected/wind-farms/'
      path: '/wind-farms'
      fullPath: '/wind-farms/'
      preLoaderRoute: typeof ProtectedWindFarmsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/wind-farms/$windfarmId': {
      id: '/_protected/wind-farms/$windfarmId'
      path: '/wind-farms/$windfarmId'
      fullPath: '/wind-farms/$windfarmId'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/portfolios/$portfolioId': {
      id: '/_protected/portfolios/$portfolioId'
      path: '/$portfolioId'
      fullPath: '/portfolios/$portfolioId'
      preLoaderRoute: typeof ProtectedPortfoliosPortfolioIdRouteImport
      parentRoute: typeof ProtectedPortfoliosRoute
    }
    '/_protected/wind-farms/$windfarmId/weather': {
      id: '/_protected/wind-farms/$windfarmId/weather'
      path: '/weather'
      fullPath: '/wind-farms/$windfarmId/weather'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdWeatherRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
    '/_protected/wind-farms/$windfarmId/market': {
      id: '/_protected/wind-farms/$windfarmId/market'
      path: '/market'
      fullPath: '/wind-farms/$windfarmId/market'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdMarketRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
    '/_protected/wind-farms/$windfarmId/generation': {
      id: '/_protected/wind-farms/$windfarmId/generation'
      path: '/generation'
      fullPath: '/wind-farms/$windfarmId/generation'
      preLoaderRoute: typeof ProtectedWindFarmsWindfarmIdGenerationRouteImport
      parentRoute: typeof ProtectedWindFarmsWindfarmIdRoute
    }
  }
}

interface ProtectedPortfoliosRouteChildren {
  ProtectedPortfoliosPortfolioIdRoute: typeof ProtectedPortfoliosPortfolioIdRoute
}

const ProtectedPortfoliosRouteChildren: ProtectedPortfoliosRouteChildren = {
  ProtectedPortfoliosPortfolioIdRoute: ProtectedPortfoliosPortfolioIdRoute,
}

const ProtectedPortfoliosRouteWithChildren =
  ProtectedPortfoliosRoute._addFileChildren(ProtectedPortfoliosRouteChildren)

interface ProtectedWindFarmsWindfarmIdRouteChildren {
  ProtectedWindFarmsWindfarmIdGenerationRoute: typeof ProtectedWindFarmsWindfarmIdGenerationRoute
  ProtectedWindFarmsWindfarmIdMarketRoute: typeof ProtectedWindFarmsWindfarmIdMarketRoute
  ProtectedWindFarmsWindfarmIdWeatherRoute: typeof ProtectedWindFarmsWindfarmIdWeatherRoute
}

const ProtectedWindFarmsWindfarmIdRouteChildren: ProtectedWindFarmsWindfarmIdRouteChildren =
  {
    ProtectedWindFarmsWindfarmIdGenerationRoute:
      ProtectedWindFarmsWindfarmIdGenerationRoute,
    ProtectedWindFarmsWindfarmIdMarketRoute:
      ProtectedWindFarmsWindfarmIdMarketRoute,
    ProtectedWindFarmsWindfarmIdWeatherRoute:
      ProtectedWindFarmsWindfarmIdWeatherRoute,
  }

const ProtectedWindFarmsWindfarmIdRouteWithChildren =
  ProtectedWindFarmsWindfarmIdRoute._addFileChildren(
    ProtectedWindFarmsWindfarmIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedComparisonRoute: typeof ProtectedComparisonRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedPortfoliosRoute: typeof ProtectedPortfoliosRouteWithChildren
  ProtectedWindFarmsWindfarmIdRoute: typeof ProtectedWindFarmsWindfarmIdRouteWithChildren
  ProtectedWindFarmsIndexRoute: typeof ProtectedWindFarmsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedComparisonRoute: ProtectedComparisonRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedPortfoliosRoute: ProtectedPortfoliosRouteWithChildren,
  ProtectedWindFarmsWindfarmIdRoute:
    ProtectedWindFarmsWindfarmIdRouteWithChildren,
  ProtectedWindFarmsIndexRoute: ProtectedWindFarmsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface DemoRouteChildren {
  DemoWindfarmRoute: typeof DemoWindfarmRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoWindfarmRoute: DemoWindfarmRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InvitationTokenRoute: InvitationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
